export function foo(x: number) {
  try {
  } catch (e) {
  } finally {
  }
  return 123;
}
